import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePatientPDF = (patient) => {
  const doc = new jsPDF();

  // Header bar
  doc.setFillColor(13, 122, 158);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("MedTrack — Patient Report", 14, 19);

  // Generated date
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 150, 19);

  // Patient info section
  doc.setTextColor(30, 42, 59);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Patient Information", 14, 44);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);

  const info = [
    ["Full Name", patient.name],
    ["Age", `${patient.age} years`],
    ["Gender", patient.gender],
    ["Phone", patient.phone || "N/A"],
  ];

  autoTable(doc, {
    startY: 48,
    head: [],
    body: info,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: "bold", textColor: [13, 122, 158], cellWidth: 40 },
      1: { textColor: [30, 42, 59] },
    },
  });

  // Medical History
  const afterInfo = doc.lastAutoTable.finalY + 8;
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 42, 59);
  doc.text("Medical History", 14, afterInfo);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);

  const history = patient.medicalHistory || "No medical history recorded.";
  const lines = doc.splitTextToSize(history, 180);
  doc.text(lines, 14, afterInfo + 8);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text("This report was generated by MedTrack. Confidential medical document.", 14, 285);

  doc.save(`${patient.name.replace(/ /g, "_")}_report.pdf`);
};